name: Portfolio Auto Sync

on:
  push:
    branches: [ main ]
    paths: [ 'portfolio.html', 'portfolio-notion.md' ]
  schedule:
    - cron: '0 9 * * 1'  # 매주 월요일 오전 9시

jobs:
  sync-portfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install puppeteer
          
      - name: Update Notion Portfolio
        env:
          NOTION_EMAIL: ${{ secrets.NOTION_EMAIL }}
          NOTION_PASSWORD: ${{ secrets.NOTION_PASSWORD }}
        run: |
          node notion-automation-alternative.js
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto sync portfolio from HTML" || exit 0
          git push
